version: "3.8"

services:
  # Servicio de Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: challenges_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenges_db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # API de Clientes (Puerto 3001)
  customers-api:
    build: ./customers-api
    container_name: customers_api_container
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=challenges_db
      - SERVICE_TOKEN=token_secreto_interno_123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # API de Ã“rdenes (Puerto 3002)
  orders-api:
    build: ./orders-api
    container_name: orders_api_container
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=challenges_db
      - SERVICE_TOKEN=token_secreto_interno_123
      # URL interna para que Orders hable con Customers
      - CUSTOMERS_API_URL=http://customers-api:3001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
