version: "3.8"

services:
  # Servicio de Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: challenges_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # API de Clientes (Puerto 3001)
  customers-api:
    build: ./customers-api
    container_name: customers_api_container
    ports:
      - "${CUSTOMERS_API_PORT}:${CUSTOMERS_API_PORT}"
    environment:
      - PORT=${CUSTOMERS_API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - SERVICE_TOKEN=${SERVICE_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # API de Ã“rdenes (Puerto 3002)
  orders-api:
    build: ./orders-api
    container_name: orders_api_container
    ports:
      - "${ORDERS_API_PORT}:${ORDERS_API_PORT}"
    environment:
      - PORT=${ORDERS_API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - SERVICE_TOKEN=${SERVICE_TOKEN}
      # URL interna para que Orders hable con Customers
      - CUSTOMERS_API_URL=${CUSTOMERS_API_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
